### ISSUE TITLE
Exe crashing

### ISSUE THREAD

**Issue by inh4les** [bootzin/SlimeSimulation#1]
Getting this error:
Unhandled exception. System.IO.FileNotFoundException: Could not find file 'C:\Windows\system32\SlimeSimUpdate.glsl'.
File name: 'C:\Windows\system32\SlimeSimUpdate.glsl'
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamReader.ValidateArgsAndOpenPath(String path, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamReader..ctor(String path)
   at System.IO.File.OpenText(String path)
   at SlimeSimulation.SlimeSimulationLayer.ReadShaderBytes(String shaderName)
   at SlimeSimulation.SlimeSimulationLayer.OnAttach()
   at BootEngine.Layers.LayerStack.PushLayer(LayerBase layer)
   at SlimeSimulation.Program..ctor(Int32 width, Int32 height, WindowState state)
   at SlimeSimulation.Program.Main(String[] args)

**Comment by inh4les** [comment]
If I manually move the file to system32 I get this issue:
Unhandled exception. SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateComputeShader(IntPtr shaderBytecodeRef, PointerSize bytecodeLength, ClassLinkage classLinkageRef, ComputeShader computeShaderOut)
   at SharpDX.Direct3D11.ComputeShader..ctor(Device device, Byte[] shaderBytecode, ClassLinkage linkage)
   at Veldrid.D3D11.D3D11Shader..ctor(Device device, ShaderDescription description)
   at Veldrid.D3D11.D3D11ResourceFactory.CreateShaderCore(ShaderDescription& description)
   at Veldrid.ResourceFactory.CreateShader(ShaderDescription& description)
   at Veldrid.ResourceFactory.CreateShader(ShaderDescription description)
   at Veldrid.SPIRV.ResourceFactoryExtensions.CreateFromSpirv(ResourceFactory factory, ShaderDescription computeShaderDescription, CrossCompileOptions options)
   at Veldrid.SPIRV.ResourceFactoryExtensions.CreateFromSpirv(ResourceFactory factory, ShaderDescription computeShaderDescription)
   at SlimeSimulation.SlimeSimulationLayer.OnAttach()
   at BootEngine.Layers.LayerStack.PushLayer(LayerBase layer)
   at SlimeSimulation.Program..ctor(Int32 width, Int32 height, WindowState state)
   at SlimeSimulation.Program.Main(String[] args)
